I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combatsystem.rpy", line 1, in script
    init 1 python:
  File "game/combatsystem.rpy", line 20, in <module>
    Red.party[1].addMove(Tackle)
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\svlaw\Downloads\renpy-6.99.12.3-sdk\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\svlaw\Downloads\renpy-6.99.12.3-sdk\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/combatsystem.rpy", line 1, in script
    init 1 python:
  File "C:\Users\svlaw\Downloads\renpy-6.99.12.3-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\svlaw\Downloads\renpy-6.99.12.3-sdk\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/combatsystem.rpy", line 20, in <module>
    Red.party[1].addMove(Tackle)
IndexError: list index out of range

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
BattleTest 1.0
